// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: grades_services.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Grades_GetStudentGrade_FullMethodName = "/grades.Grades/GetStudentGrade"
)

// GradesClient is the client API for Grades service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type GradesClient interface {
	// Sends a greeting
	GetStudentGrade(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeReply, error)
}

type gradesClient struct {
	cc grpc.ClientConnInterface
}

func NewGradesClient(cc grpc.ClientConnInterface) GradesClient {
	return &gradesClient{cc}
}

func (c *gradesClient) GetStudentGrade(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeReply)
	err := c.cc.Invoke(ctx, Grades_GetStudentGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GradesServer is the server API for Grades service.
// All implementations must embed UnimplementedGradesServer
// for forward compatibility.
//
// The greeting service definition.
type GradesServer interface {
	// Sends a greeting
	GetStudentGrade(context.Context, *GradeRequest) (*GradeReply, error)
	mustEmbedUnimplementedGradesServer()
}

// UnimplementedGradesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGradesServer struct{}

func (UnimplementedGradesServer) GetStudentGrade(context.Context, *GradeRequest) (*GradeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentGrade not implemented")
}
func (UnimplementedGradesServer) mustEmbedUnimplementedGradesServer() {}
func (UnimplementedGradesServer) testEmbeddedByValue()                {}

// UnsafeGradesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GradesServer will
// result in compilation errors.
type UnsafeGradesServer interface {
	mustEmbedUnimplementedGradesServer()
}

func RegisterGradesServer(s grpc.ServiceRegistrar, srv GradesServer) {
	// If the following call pancis, it indicates UnimplementedGradesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Grades_ServiceDesc, srv)
}

func _Grades_GetStudentGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradesServer).GetStudentGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grades_GetStudentGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradesServer).GetStudentGrade(ctx, req.(*GradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Grades_ServiceDesc is the grpc.ServiceDesc for Grades service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grades_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grades.Grades",
	HandlerType: (*GradesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentGrade",
			Handler:    _Grades_GetStudentGrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grades_services.proto",
}
