// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: grades-microservice.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GradesService_GetCourseGrades_FullMethodName          = "/grades.GradesService/GetCourseGrades"
	GradesService_GetStudentCourseGrades_FullMethodName   = "/grades.GradesService/GetStudentCourseGrades"
	GradesService_AddSingleGrade_FullMethodName           = "/grades.GradesService/AddSingleGrade"
	GradesService_UpdateSingleGrade_FullMethodName        = "/grades.GradesService/UpdateSingleGrade"
	GradesService_RemoveSingleGrade_FullMethodName        = "/grades.GradesService/RemoveSingleGrade"
	GradesService_GetStudentSemesterGrades_FullMethodName = "/grades.GradesService/GetStudentSemesterGrades"
)

// GradesServiceClient is the client API for GradesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GradesService is a microservice responsible for managing grades.
type GradesServiceClient interface {
	// GetCourseGrades returns all students grades enrolled in a specific course for a specific semester.
	GetCourseGrades(ctx context.Context, in *GetCourseGradesRequest, opts ...grpc.CallOption) (*GetCourseGradesResponse, error)
	// GetStudentCourseGrades returns a specific student all grades in a specific course for a specific semester.
	GetStudentCourseGrades(ctx context.Context, in *GetStudentCourseGradesRequest, opts ...grpc.CallOption) (*GetStudentCourseGradesResponse, error)
	// AddSingleGrade adds a single grade for a student in a course for a specific semester.
	AddSingleGrade(ctx context.Context, in *AddSingleGradeRequest, opts ...grpc.CallOption) (*AddSingleGradeResponse, error)
	// UpdateSingleGrade updates a single grade for a student in a course for a specific semester.
	UpdateSingleGrade(ctx context.Context, in *UpdateSingleGradeRequest, opts ...grpc.CallOption) (*UpdateSingleGradeResponse, error)
	// RemoveSingleGrade removes a single grade for a student in a course for a specific semester.
	RemoveSingleGrade(ctx context.Context, in *RemoveSingleGradeRequest, opts ...grpc.CallOption) (*RemoveSingleGradeResponse, error)
	// GetStudentSemesterGrades returns all grades for a specific student for a specific semester.
	GetStudentSemesterGrades(ctx context.Context, in *GetStudentSemesterGradesRequest, opts ...grpc.CallOption) (*GetStudentSemesterGradesResponse, error)
}

type gradesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGradesServiceClient(cc grpc.ClientConnInterface) GradesServiceClient {
	return &gradesServiceClient{cc}
}

func (c *gradesServiceClient) GetCourseGrades(ctx context.Context, in *GetCourseGradesRequest, opts ...grpc.CallOption) (*GetCourseGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourseGradesResponse)
	err := c.cc.Invoke(ctx, GradesService_GetCourseGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradesServiceClient) GetStudentCourseGrades(ctx context.Context, in *GetStudentCourseGradesRequest, opts ...grpc.CallOption) (*GetStudentCourseGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentCourseGradesResponse)
	err := c.cc.Invoke(ctx, GradesService_GetStudentCourseGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradesServiceClient) AddSingleGrade(ctx context.Context, in *AddSingleGradeRequest, opts ...grpc.CallOption) (*AddSingleGradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSingleGradeResponse)
	err := c.cc.Invoke(ctx, GradesService_AddSingleGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradesServiceClient) UpdateSingleGrade(ctx context.Context, in *UpdateSingleGradeRequest, opts ...grpc.CallOption) (*UpdateSingleGradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSingleGradeResponse)
	err := c.cc.Invoke(ctx, GradesService_UpdateSingleGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradesServiceClient) RemoveSingleGrade(ctx context.Context, in *RemoveSingleGradeRequest, opts ...grpc.CallOption) (*RemoveSingleGradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSingleGradeResponse)
	err := c.cc.Invoke(ctx, GradesService_RemoveSingleGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradesServiceClient) GetStudentSemesterGrades(ctx context.Context, in *GetStudentSemesterGradesRequest, opts ...grpc.CallOption) (*GetStudentSemesterGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentSemesterGradesResponse)
	err := c.cc.Invoke(ctx, GradesService_GetStudentSemesterGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GradesServiceServer is the server API for GradesService service.
// All implementations must embed UnimplementedGradesServiceServer
// for forward compatibility.
//
// GradesService is a microservice responsible for managing grades.
type GradesServiceServer interface {
	// GetCourseGrades returns all students grades enrolled in a specific course for a specific semester.
	GetCourseGrades(context.Context, *GetCourseGradesRequest) (*GetCourseGradesResponse, error)
	// GetStudentCourseGrades returns a specific student all grades in a specific course for a specific semester.
	GetStudentCourseGrades(context.Context, *GetStudentCourseGradesRequest) (*GetStudentCourseGradesResponse, error)
	// AddSingleGrade adds a single grade for a student in a course for a specific semester.
	AddSingleGrade(context.Context, *AddSingleGradeRequest) (*AddSingleGradeResponse, error)
	// UpdateSingleGrade updates a single grade for a student in a course for a specific semester.
	UpdateSingleGrade(context.Context, *UpdateSingleGradeRequest) (*UpdateSingleGradeResponse, error)
	// RemoveSingleGrade removes a single grade for a student in a course for a specific semester.
	RemoveSingleGrade(context.Context, *RemoveSingleGradeRequest) (*RemoveSingleGradeResponse, error)
	// GetStudentSemesterGrades returns all grades for a specific student for a specific semester.
	GetStudentSemesterGrades(context.Context, *GetStudentSemesterGradesRequest) (*GetStudentSemesterGradesResponse, error)
	mustEmbedUnimplementedGradesServiceServer()
}

// UnimplementedGradesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGradesServiceServer struct{}

func (UnimplementedGradesServiceServer) GetCourseGrades(context.Context, *GetCourseGradesRequest) (*GetCourseGradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseGrades not implemented")
}
func (UnimplementedGradesServiceServer) GetStudentCourseGrades(context.Context, *GetStudentCourseGradesRequest) (*GetStudentCourseGradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentCourseGrades not implemented")
}
func (UnimplementedGradesServiceServer) AddSingleGrade(context.Context, *AddSingleGradeRequest) (*AddSingleGradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSingleGrade not implemented")
}
func (UnimplementedGradesServiceServer) UpdateSingleGrade(context.Context, *UpdateSingleGradeRequest) (*UpdateSingleGradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSingleGrade not implemented")
}
func (UnimplementedGradesServiceServer) RemoveSingleGrade(context.Context, *RemoveSingleGradeRequest) (*RemoveSingleGradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSingleGrade not implemented")
}
func (UnimplementedGradesServiceServer) GetStudentSemesterGrades(context.Context, *GetStudentSemesterGradesRequest) (*GetStudentSemesterGradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentSemesterGrades not implemented")
}
func (UnimplementedGradesServiceServer) mustEmbedUnimplementedGradesServiceServer() {}
func (UnimplementedGradesServiceServer) testEmbeddedByValue()                       {}

// UnsafeGradesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GradesServiceServer will
// result in compilation errors.
type UnsafeGradesServiceServer interface {
	mustEmbedUnimplementedGradesServiceServer()
}

func RegisterGradesServiceServer(s grpc.ServiceRegistrar, srv GradesServiceServer) {
	// If the following call pancis, it indicates UnimplementedGradesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GradesService_ServiceDesc, srv)
}

func _GradesService_GetCourseGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradesServiceServer).GetCourseGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradesService_GetCourseGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradesServiceServer).GetCourseGrades(ctx, req.(*GetCourseGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradesService_GetStudentCourseGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentCourseGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradesServiceServer).GetStudentCourseGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradesService_GetStudentCourseGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradesServiceServer).GetStudentCourseGrades(ctx, req.(*GetStudentCourseGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradesService_AddSingleGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSingleGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradesServiceServer).AddSingleGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradesService_AddSingleGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradesServiceServer).AddSingleGrade(ctx, req.(*AddSingleGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradesService_UpdateSingleGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSingleGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradesServiceServer).UpdateSingleGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradesService_UpdateSingleGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradesServiceServer).UpdateSingleGrade(ctx, req.(*UpdateSingleGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradesService_RemoveSingleGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSingleGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradesServiceServer).RemoveSingleGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradesService_RemoveSingleGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradesServiceServer).RemoveSingleGrade(ctx, req.(*RemoveSingleGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradesService_GetStudentSemesterGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentSemesterGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradesServiceServer).GetStudentSemesterGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradesService_GetStudentSemesterGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradesServiceServer).GetStudentSemesterGrades(ctx, req.(*GetStudentSemesterGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GradesService_ServiceDesc is the grpc.ServiceDesc for GradesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GradesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grades.GradesService",
	HandlerType: (*GradesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCourseGrades",
			Handler:    _GradesService_GetCourseGrades_Handler,
		},
		{
			MethodName: "GetStudentCourseGrades",
			Handler:    _GradesService_GetStudentCourseGrades_Handler,
		},
		{
			MethodName: "AddSingleGrade",
			Handler:    _GradesService_AddSingleGrade_Handler,
		},
		{
			MethodName: "UpdateSingleGrade",
			Handler:    _GradesService_UpdateSingleGrade_Handler,
		},
		{
			MethodName: "RemoveSingleGrade",
			Handler:    _GradesService_RemoveSingleGrade_Handler,
		},
		{
			MethodName: "GetStudentSemesterGrades",
			Handler:    _GradesService_GetStudentSemesterGrades_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grades-microservice.proto",
}
